# Generated by Django 2.2.12 on 2023-09-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_projectupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
