# Generated by Django 2.2.12 on 2023-09-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_projectupdate_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='ids',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
